config/routes.rb
Rails.application.routes.draw do
  root to: 'staticpages#home'

  get '/users/list', to: 'pages#users'

  get '/main', to: 'pages#main'
  post '/main', to: 'pages#new_record'

  get '/events', to: 'pages#events'
  post '/events', to: 'pages#create'
  delete '/events', to: 'pages#destroy'

  get '/myworks', to: 'pages#myworks'
  post '/myworks', to: 'pages#myworks_create'

  get '/feed', to: 'pages#feed'

  get '/chart', to: 'charts#show'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get '/users/:id/following', to: 'relationships#following', as: :following_user
  get '/users/:id/followers', to: 'relationships#followers', as: :followers_user

  resources :relationships, only: %i[create destroy]
end

app/views/shared/_img_thumb.html.erb
<%= image_tag current_user.image.thumb.url, class: "rounded-circle", size: "32" %>
<%= current_user.name %>

app/views/shared/_new_schedule.html.erb
<div class="d-flex justify-content-center my-3">
  <%= image_tag "workout.png", size: '24', class: "my-auto" %>
  <h4 class="my-auto">Add new schedule </h4>
</div>

<%= form_for(@new_record, url:main_path) do |f| %>
  <div class="form-group justify-content-around">
    <%= f.hidden_field :user_id %>
          
    <div class="form-group col">
      <%= f.date_field :start_time, class: 'form-control', placeholder: "Start_time", required: true  %>
    </div>

    <div class="form-group col">
      <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
    </div>

    <div class="form-group col">
      <%= f.text_area :description, class: 'form-control', placeholder: "Description"  %>
    </div>

    <div class="actions col">
      <%= f.submit "Add", class: "btn btn-warning form-control" %>
    </div>
  </div>
<% end %>

app/views/shared/_record_card.html.erb
<div class="card mx-auto my-4 p-3">
  <div class="mb-3">
    <span class="badge badge-info"><%= record.start_time %></span>
  </div>
  <div class="card-columns mb-2">
    <%= image_tag record.user.image.thumb.url, class: "rounded-circle", size: "48" %>
    <a id="modal-open-<%= record.id %>" class="button-link align-middle ml-2" style="font-size: 24px"><%= record.user.name %></a>
    <div id="<%= record.id %>" class="modal-content fixed-top">
      <%= render partial: 'shared/user_status', locals: {user_check: record.user} %>
      <p class="text-right"><a id="modal-close" class="button-link">exit</a></p>
    </div>
  </div>
  <div class="mb-3">
    <h4 class="card-title">
      <% if record.user == current_user %>
        <%= link_to record.title, events_path(start_time: record.start_time) %>
      <% else %>
        <p><%= record.title %></p>
      <% end %>
    </h4>
    <p class="card-text"><%= record.description %></p>
  </div>
  <table class="table">
    <tr>
      <th>Name</th>
      <th>Set</th>
      <th>Rep</th>
      <th>Weight</th>
      <th>Vol</th>
    </tr>
    <% record.workout.each do |workout| %>
    <tr>
      <td><%= workout.mywork.name %></td>
      <td><%= workout.set %></td>
      <td><%= workout.rep %></td>
      <td><%= workout.weight %></td>
      <td><%= workout.vol %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/shared/_stats.html.erb
<div class="stats">
  <strong id="following" class="stat">
    <%= link_to user_check.following.count.to_s + " following", following_user_path(user_check), id: user_check.id %>
  </strong>
  <strong id="followers" class="stat ml-2">
    <%= link_to user_check.followers.count.to_s + " followers", followers_user_path(user_check), id: user_check.id %>
  </strong>
</div>

app/views/shared/_user_card.html.erb
<div class="d-flex row">
  <% @users.each do |user| %>
    <div class="p-3 mr-3 card text-center" style="width:150px">
      <%= image_tag user.image.url, class: "rounded-circle mx-auto", size: "100" %>
      <%= user.name %>
      <% if current_user == user_check %>
        <% if current_user.following?(user) %>
            <%= form_for(current_user.active_relationships.find_by(followed_id: user.id), html: { method: :delete }) do |f| %>
              <%= f.submit "Unfollow", class: "btn btn-secondary" %>
            <% end %>
        <% else %>
            <%= form_for(current_user.active_relationships.build) do |f| %>
              <div><%= hidden_field_tag :followed_id, user.id %></div>
              <%= f.submit "Follow", class: "btn btn-primary" %>
            <% end %>
        <% end %>
      <% end %>
    </div> 
  <% end %>
</div>

app/views/shared/_user_status.html.erb
<div class="card-columns d-flex justify-content-start p-1">
  <%= image_tag user_check.image.url, class: "rounded-circle", size: "96" %>
  <div class="align-self-center ml-4 p-1">
    <h4><%= user_check.name %></h4>
    <h6><%= user_check.record.count %> records</h6>
  </div>
</div>
<div class="p-1">
  <%= render partial: 'shared/stats', locals: {user_check: user_check} %>
</div>
<div class="p-1 border-top">
  <% if user_check.description.present? %>
    <%= user_check.description %>
  <% elsif current_user == user_check %>
    Please introduce yourself from <%= link_to "here", edit_user_registration_path, class: "badge badge-primary" %>
  <% end %>
</div>