config/routes.rb
Rails.application.routes.draw do
  root to: 'staticpages#home'

  get '/users/list', to: 'pages#users'

  get '/main', to: 'pages#main'
  post '/main', to: 'pages#new_record'

  get '/events', to: 'pages#events'
  post '/events', to: 'pages#create'
  delete '/events', to: 'pages#destroy'

  get '/myworks', to: 'pages#myworks'
  post '/myworks', to: 'pages#myworks_create'

  get '/feed', to: 'pages#feed'

  get '/chart', to: 'charts#show'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get '/users/:id/following', to: 'relationships#following', as: :following_user
  get '/users/:id/followers', to: 'relationships#followers', as: :followers_user

  resources :relationships, only: %i[create destroy]
end

app/views/pages/events.html.erb
<div class="justify-content-center p-3">
  <div class="p-2 mx-auto col-lg-7">
    <%= render partial: 'shared/record_card', locals:{record: @record} %>

    <div>
      <%= form_for(:workout, url:events_path) do |f| %>
        <div class="input-group">
          <%= f.hidden_field :record_id, value: @record.id %>

          <%= f.select :mywork_id, options_from_collection_for_select(@myworks, :id, :name), {}, {class: 'custom-select'} %>
          <%= f.text_field :set, class: 'form-control', placeholder: "Set", required: true %>
          <%= f.text_field :rep, class: 'form-control', placeholder: "Rep", required: true %>
          <%= f.text_field :weight, class: 'form-control', placeholder: "Weight", required: true %>

          <div class="input-group-append">
            <%= f.submit "Add", class: "btn btn-warning" %>
          </div>
        </div>
      <% end %>
      <%= link_to "click here", myworks_path, class: "badge badge-primary" %> to add your own workout list!
    </div>
  </div>
</div>

app/views/pages/feed.html.erb
<div class="container-fluid p-3">
  <div class="row">
    <div class="p-2 col-lg-4">
      <div class="card mx-3 p-3">
        <%= render partial: 'shared/user_status', locals: {user_check: @user} %>
      </div>
      <%= render 'shared/new_schedule' %>
    </div>
    <div class="p-2 col-lg-8">
      <%= form_tag(users_list_path, method: "get", class: "input-group mb-3") do %>
        <%= text_field_tag :search, '', class: 'form-control', placeholder: "Please enter username", required:true  %>
        <div class="input-group-append">
          <%= submit_tag 'Search', name: nil, class:"btn btn-warning", style:"z-index:1" %> 
        </div>
      <% end %>
      <%= render partial: 'shared/record_card', collection: @records, as: :record %>
      <%= will_paginate @records, list_classes: %w(pagination justify-content-center) %>
    </div>
  </div>
</div>

<script>
<% @records.each do |record| %>
  $("#modal-open-<%= record.id %>").click(
    function(){
      $(this).blur() ;
      if($("#modal-overlay")[0]) return false ;	
      $("body").append('<div id="modal-overlay"></div>');
      $("#modal-overlay").fadeIn("slow");
      $('#<%= record.id %>').fadeIn("slow");
    }
  );
<% end %>

$("#modal-overlay,#modal-close").unbind().click(function(){
    $(".modal-content,#modal-overlay").fadeOut("slow",function(){
    $("#modal-overlay").remove();
  });
});

</script>

app/views/pages/main.html.erb
<div class="container-fluid p-3">
  <div class="row">
    <div class="col-lg-8">
      <%= month_calendar events: @records do |date, records| %>
        <%= date.day %>

        <% records.each do |record| %>
          <div>
            <%= link_to image_tag("workout.png", width: '18') + "Details", events_path(start_time: record.start_time), class: "text-muted text-center" %> 
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="col-lg-4">
      <%= render 'shared/new_schedule' %>
    </div>
  </div>
</div>

app/views/pages/myworks.erb
<div class="justify-content-center p-3">
  <div class="p-2 mx-auto col-lg-7">
    <div class="card mx-auto" style="padding:10px; margin-bottom:20px">
      <table class="table">
        <div class="m-3 text-center">
          <h2>Mywork</h2>
        </div>
        <tr>
          <th>Name</th>
          <th>Description</th>
        </tr>
        <% @myworks.each do |myworks| %>
          <tr>
            <td><%= myworks.name %></td>
            <td><%= myworks.description %></td>
          </tr>
        <% end %>
      </table>
    </div>
    <div>
      <%= form_for(:mywork, url:myworks_path) do |f| %>
        <div class="form-group justify-content-around">
          <%= f.hidden_field :user_id, value: current_user.id %>

          <div class="form-group">
            <%= f.text_field :name, class: 'form-control', placeholder: "Title", required: true %>
          </div>
      
          <div class="form-group">
            <%= f.text_area :description, class: 'form-control', placeholder: "Description"  %>
          </div>
      
          <div class="actions">
            <%= f.submit "Add", class: "btn btn-warning form-control" %>
          </div>

        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pages/users.html.erb
<div class="container-fluid p-3">
  <div class="d-flex justify-content-around row">
    <div class="p-2 align-self-start col-lg-4">
      <div class="card mx-3 p-3">
        <%= render partial: 'shared/user_status', locals: {user_check: current_user} %>
      </div>
    </div>  
    <div class="p-2 col-lg-7">
      <h3>User list</h3>
      <%= render partial: 'shared/user_card', locals: {user_check: current_user} %>
      <%= will_paginate @users, list_classes: %w(pagination justify-content-center) %>
    </div>
  </div>
</div>