config/routes.rb
Rails.application.routes.draw do
  root to: 'staticpages#home'

  get '/users/list', to: 'pages#users'

  get '/main', to: 'pages#main'
  post '/main', to: 'pages#new_record'

  get '/events', to: 'pages#events'
  post '/events', to: 'pages#create'
  delete '/events', to: 'pages#destroy'

  get '/myworks', to: 'pages#myworks'
  post '/myworks', to: 'pages#myworks_create'

  get '/feed', to: 'pages#feed'

  get '/chart', to: 'charts#show'

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations'
  }

  get '/users/:id/following', to: 'relationships#following', as: :following_user
  get '/users/:id/followers', to: 'relationships#followers', as: :followers_user

  resources :relationships, only: %i[create destroy]
end

app/views/layouts/_header.html.erb
<header style="margin-bottom:62px">
  <div class="container-fluid">
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
      <%= link_to image_tag("dumbel.png", width: '36') + " Loffets", root_path, class: "navbar-brand", align: "middle"%>
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
        <% else %>
          <li class="nav-item">
            <%= link_to "About", "#about", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Feature", "#feature", class: "nav-link" %>
          </li>
        <% end %>
      </ul>

      <% if user_signed_in? %>
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <%= link_to (render 'shared/img_thumb'), "#", class: "active nav-link dropdown-toggle", data: {toggle:"dropdown"}, aria: {haspopup:"true", expanded:"false"} %>
          <div class="dropdown-menu dropdown-menu-right py-1">
            <%= link_to "Main", main_path, class: "dropdown-item" %>
            <%= link_to "Feed", feed_path, class: "dropdown-item" %>
            <%= link_to "Chart", chart_path, class: "dropdown-item" %>
            <%= link_to "Profile", edit_user_registration_path, class: "dropdown-item" %>
          <div class="dropdown-divider my-1"></div>
            <%= link_to "SignOut", destroy_user_session_path, class: "dropdown-item", method: :delete %>
          </div>
        </li>
      </ul>

      <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "SignIn", new_user_session_path, class: "active nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "SignUp", new_user_registration_path, class: "active nav-link" %>
        </li>
      </ul>
      <% end %>

    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container-fluid bg-light">
    <%= render 'layouts/header' %>
    <% unless notice.nil? %>
      <div class="alert alert-success alert-dismissible fade show m-0" role="alert">
        <%= notice %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <% unless alert.nil? %>
      <div class="alert alert-danger alert-dismissible fade show m-0" role="alert">
        <%= alert %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>